### ISSUE TITLE
Starting a match

### ISSUE THREAD

**Issue by daniel022302** [IrishPacks/ArenaPvP#11]
When you start a match using the swords it show you the kits but when you press them nothing happens. when you throw them doesn't work. even /duel

Basically you can't play the kits 

![screenshot_20171001-212008](https://user-images.githubusercontent.com/28458532/31058616-8f616580-a6ee-11e7-91f8-b2524e4c6973.png)

**Comment by IrishPacks** [comment]
Like I said, please use the latest version, I have verified that it works.

**Comment by daniel022302** [comment]
Do you have a server where I can test this . If you want to test it on my server for proof

**Comment by IrishPacks** [comment]
Please make sure you are using the latest Pocketmine-MP version to go along with this. 

This is what should happen: ![](https://imgur.com/a/rh4Bg)

**Comment by IrishPacks** [comment]
Let me know if it's fixed when using a different version.

**Comment by daniel022302** [comment]
Using Latest Successful Pmmp build 3.0.0-Alpha9 still doesn't work

**Comment by IrishPacks** [comment]
And are you using the latest version of the plugin?

**Comment by daniel022302** [comment]
Yes if you wanna see what happens join this server 51.255.15.252:19132

**Comment by IrishPacks** [comment]
Whitelist me: IrishPlugins

**Comment by daniel022302** [comment]
Done

**Comment by IrishPacks** [comment]
Works for me, but I'm guessing it's the OS.
