### ISSUE TITLE
starting a Match

### ISSUE THREAD

**Issue by daniel022302** [IrishPacks/ArenaPvP#13]
02.10 23:19:52 [Server] Server thread/CRITICAL Could not execute task sys\arenapvp\match\MatchHeartbeat: Return value of sys\arenapvp\match\Match::hasStarted() must be of the type boolean, null returned
02.10 23:19:52 [Server] Server thread/CRITICAL TypeError: "Return value of sys\arenapvp\match\Match::hasStarted() must be of the type boolean, null returned" (EXCEPTION) in "ArenaPvP-master/src/sys/arenapvp/match/Match" at line 278
02.10 23:19:52 [Server] Server thread/DEBUG #0 ArenaPvP-master/src/sys/arenapvp/match/Match(297): sys\arenapvp\match\Match->hasStarted()
02.10 23:19:52 [Server] Server thread/DEBUG #1 ArenaPvP-master/src/sys/arenapvp/match/MatchManager(51): sys\arenapvp\match\Match->tick()
02.10 23:19:52 [Server] Server thread/DEBUG #2 ArenaPvP-master/src/sys/arenapvp/match/MatchHeartbeat(40): sys\arenapvp\match\MatchManager->tickMatches()
02.10 23:19:52 [Server] Server thread/DEBUG #3 src/pocketmine/scheduler/TaskHandler(160): sys\arenapvp\match\MatchHeartbeat->onRun(integer 1441)
02.10 23:19:52 [Server] Server thread/DEBUG #4 src/pocketmine/scheduler/ServerScheduler(326): pocketmine\scheduler\TaskHandler->run(integer 1441)
02.10 23:19:52 [Server] Server thread/DEBUG #5 src/pocketmine/Server(2512): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 1441)
02.10 23:19:52 [Server] Server thread/DEBUG #6 src/pocketmine/Server(2257): pocketmine\Server->tick()
02.10 23:19:52 [Server] Server thread/DEBUG #7 src/pocketmine/Server(2136): pocketmine\Server->tickProcessor()
02.10 23:19:52 [Server] Server thread/DEBUG #8 src/pocketmine/Server(1718): pocketmine\Server->start()
02.10 23:19:52 [Server] Server thread/DEBUG #9 src/pocketmine/PocketMine(556): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///custom-php7.2.phar/, string /, string /plugins/)
02.10 23:19:52 [Server] Server thread/DEBUG #10 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)

**Comment by IrishPacks** [comment]
Please stop spamming the issue tracker with already known issues.

**Comment by daniel022302** [comment]
I was just trying to remind you so you can see it. I don't mean anything bad. I'm sorry
