### ISSUE TITLE
Arena Manager

### ISSUE THREAD

**Issue by daniel022302** [IrishPacks/ArenaPvP#15]
04.10 14:10:40[Server] Server thread/CRITICAL TypeError: "Return value of sys\arenapvp\ArenaCommandManager::getIndividualCommandData() must be of the type string or null, array returned" (EXCEPTION) in "ArenaPvP-master/src/sys/arenapvp/ArenaCommandManager" at line 48
04.10 14:10:40[Server] Server thread/DEBUG #0 ArenaPvP-master/src/sys/arenapvp/basefiles/BaseArenaCommand(29): sys\arenapvp\ArenaCommandManager->getIndividualCommandData(string duel)
04.10 14:10:40[Server] Server thread/DEBUG #1 ArenaPvP-master/src/sys/arenapvp/basefiles/BaseArenaCommand(23): sys\arenapvp\basefiles\BaseArenaCommand->setCommandData()
04.10 14:10:40[Server] Server thread/DEBUG #2 ArenaPvP-master/src/sys/arenapvp/basefiles/BaseArenaUserCommand(20): sys\arenapvp\basefiles\BaseArenaCommand->__construct(sys\arenapvp\ArenaPvP object, string duel, string Duel other players, string /duel [player], array Array(), NULL )
04.10 14:10:40[Server] Server thread/DEBUG #3 ArenaPvP-master/src/sys/arenapvp/command/DuelCommand(21): sys\arenapvp\basefiles\BaseArenaUserCommand->__construct(sys\arenapvp\ArenaPvP object, string duel, string Duel other players, string /duel [player])
04.10 14:10:40[Server] Server thread/DEBUG #4 ArenaPvP-master/src/sys/arenapvp/ArenaCommandManager(29): sys\arenapvp\command\DuelCommand->__construct(sys\arenapvp\ArenaPvP object)
04.10 14:10:40[Server] Server thread/DEBUG #5 ArenaPvP-master/src/sys/arenapvp/ArenaPvP(74): sys\arenapvp\ArenaCommandManager->initCommands(sys\arenapvp\ArenaPvP object)
04.10 14:10:40[Server] Server thread/DEBUG #6 ArenaPvP-master/src/sys/arenapvp/ArenaPvP(52): sys\arenapvp\ArenaPvP->loadCommandManager()
04.10 14:10:40[Server] Server thread/DEBUG #7 src/pocketmine/plugin/PluginBase(90): sys\arenapvp\ArenaPvP->onEnable()
04.10 14:10:40[Server] Server thread/DEBUG #8 DevTools (1).phar/src/FolderPluginLoader/FolderPluginLoader(125): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
04.10 14:10:40[Server] Server thread/DEBUG #9 src/pocketmine/plugin/PluginManager(610): FolderPluginLoader\FolderPluginLoader->enablePlugin(sys\arenapvp\ArenaPvP object)
04.10 14:10:40[Server] Server thread/DEBUG #10 src/pocketmine/Server(1944): pocketmine\plugin\PluginManager->enablePlugin(sys\arenapvp\ArenaPvP object)
04.10 14:10:40[Server] Server thread/DEBUG #11 src/pocketmine/Server(1930): pocketmine\Server->enablePlugin(sys\arenapvp\ArenaPvP object)
04.10 14:10:40[Server] Server thread/DEBUG #12 src/pocketmine/Server(1716): pocketmine\Server->enablePlugins(integer 1)
04.10 14:10:40[Server] Server thread/DEBUG #13 src/pocketmine/PocketMine(556): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///custom-php7.2.phar/, string /, string /plugins/)
04.10 14:10:40[Server] Server thread/DEBUG #14 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)
04.10 14:10:40[Server]Server thread/INFO Disabling ArenaPvP v1.2.0
RAW Paste Data

**Comment by IrishPacks** [comment]
Fixed, just haven't committed.
