### ISSUE TITLE
maybe someone should make arenas load with a generator ?

### ISSUE THREAD

**Issue by FRISCOWZMCPE** [IrishPacks/ArenaPvP#18]
making a Generator for arenas must be a good idea to not have issues with not having Enough of free arenas ?

**Comment by JackNoordhuis** [comment]
Are you really that lazy?

**Comment by FRISCOWZMCPE** [comment]
Yes I am. (btw i just wanted to help lol i'm not using the plugin)

**Comment by IrishPacks** [comment]
Badlion *does* do it this way, but that'd create chaos with the new chunk loader.

**Comment by JackNoordhuis** [comment]
A generator implies all the arenas are created somewhat randomly with code, I believe the correct terminology would be a populator – the empty chunks are generated and then populated with the pre-defined arenas.

**Comment by FRISCOWZMCPE** [comment]
should i make a Pull Request to make a Generator or not ?

**Comment by IrishPacks** [comment]
I have ideas about implementing this, but yeah populator seems more fitting. Anyways, do whatever you feel like. If I feel that it's good, I'll accept it.

**Comment by FRISCOWZMCPE** [comment]
Okay i will do a flat Arena Generator :)

**Comment by FRISCOWZMCPE** [comment]
tried something here https://github.com/FRISCOWZMCPE/ArenaPvP

**Comment by FRISCOWZMCPE** [comment]
what are your thoughts on it lol ?

**Comment by IrishPacks** [comment]
It's not optimal whatsoever, plus it's just a copy and pasted regular generator with changed values to make one arena only. Scroll up and you can see we're looking for a populator, not a generator.

**Comment by JackNoordhuis** [comment]
My initial response to this thread are my thoughts on what you've got so far. As we discussed prior to my initial response, a populator that loads a bunch of already created arenas stored in schematic (or some other format) as required is what we're after; not a generator to create whole new arenas.

**Comment by FRISCOWZMCPE** [comment]
Oh okay i will try to do something
