### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by daniel022302** [IrishPacks/ArenaPvP#2]
There's a problem with it.
First it says it depends on a CORE and I removed it now it says this
01.10 16:17:39 [Server] Server thread/CRITICAL Error: "Class 'sys\irish\utils\Permissions' not found" (EXCEPTION) in "ArenaPvP-master/src/sys/arenapvp/command/EditEloCommand" at line 24

**Comment by IrishPacks** [comment]
I'll need to know where it said that it depended on a core, so I can fix it.

**Comment by daniel022302** [comment]
plugin.yml

**Comment by IrishPacks** [comment]
Fixed.
