### ISSUE TITLE
Update this to API 11

### ISSUE THREAD

**Issue by artulloss** [IrishPacks/ArenaPvP#20]
This plugin sounds amazing but when using on API 11 it states that the commands need to be run in game, but I am in game so it's broke. There is probably more needed done but this plugin is amazing and I'd love to get to use it for my server as well as see other servers with it.

**Comment by artulloss** [comment]
Rip I'm paying $200 for a rewrite from scratch

**Comment by IrishPacks** [comment]
Ah well, I've been meaning to work on it. I'll start updating it soon.
