### ISSUE TITLE
 The unranked and ranked items do not go fix it please

### ISSUE THREAD

**Issue by Gtafgu** [IrishPacks/ArenaPvP#28]
##Issue

##Versions

- Plugin:
- Pocketmine-MP:
- PHP:

##Details to help reproduce issue

List any details or steps to help reproduce the issue.

##Further comments, backtraces, etc.
Submit anything that you believe is necessary in solving the issue.

Please avoid submitting full errors without markdown. Use tools
such as Pastebin, Github Gist, etc. to make the errors readable.

**Comment by IrishPacks** [comment]
Without knowing your Pocketmine or plugin version as well as steps to reproduce the issue, I cannot help  whatsoever.
