### ISSUE TITLE
Plugin Issues

### ISSUE THREAD

**Issue by daniel022302** [IrishPacks/ArenaPvP#3]
Bugs?

01.10 17:42:34 [Server] Server thread/INFO Loading DevTools v1.12.3.2
01.10 17:42:34 [Server] Server thread/INFO Enabling DevTools v1.12.3.2
01.10 17:42:34 [Server] Server thread/INFO Loading source plugin ArenaPvP v1.2.0
01.10 17:42:34 [Server] Server thread/CRITICAL RuntimeException: "Trying to overwrite an already registered item" (EXCEPTION) in "src/pocketmine/item/ItemFactory" at line 276
01.10 17:42:34 [Server] Server thread/DEBUG #0 ArenaPvP-master/src/sys/arenapvp/kit/KitManager(38): pocketmine\item\ItemFactory::registerItem(sys\arenapvp\utils\CustomBow object)
01.10 17:42:34 [Server] Server thread/DEBUG #1 ArenaPvP-master/src/sys/arenapvp/ArenaPvP(82): sys\arenapvp\kit\KitManager->__construct(sys\arenapvp\ArenaPvP object)
01.10 17:42:34 [Server] Server thread/DEBUG #2 ArenaPvP-master/src/sys/arenapvp/ArenaPvP(48): sys\arenapvp\ArenaPvP->loadKitManager()
01.10 17:42:35 [Server] Server thread/DEBUG #3 DevTools.phar/src/FolderPluginLoader/FolderPluginLoader(115): sys\arenapvp\ArenaPvP->onLoad()
01.10 17:42:35 [Server] Server thread/DEBUG #4 DevTools.phar/src/FolderPluginLoader/FolderPluginLoader(66): FolderPluginLoader\FolderPluginLoader->initPlugin(sys\arenapvp\ArenaPvP object, pocketmine\plugin\PluginDescription object, string /plugins/ArenaPvP, string /plugins/ArenaPvP-master)
01.10 17:42:35 [Server] Server thread/DEBUG #5 src/pocketmine/plugin/PluginManager(161): FolderPluginLoader\FolderPluginLoader->loadPlugin(string /plugins/ArenaPvP-master)
01.10 17:42:35 [Server] Server thread/DEBUG #6 src/pocketmine/plugin/PluginManager(305): pocketmine\plugin\PluginManager->loadPlugin(string /plugins/ArenaPvP-master, array Array())
01.10 17:42:35 [Server] Server thread/DEBUG #7 DevTools.phar/src/DevTools/DevTools(47): pocketmine\plugin\PluginManager->loadPlugins(string /plugins/, array Array())
01.10 17:42:35 [Server] Server thread/DEBUG #8 src/pocketmine/plugin/PluginBase(90): DevTools\DevTools->onEnable()
01.10 17:42:35 [Server] Server thread/DEBUG #9 src/pocketmine/plugin/PharPluginLoader(122): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
01.10 17:42:35 [Server] Server thread/DEBUG #10 src/pocketmine/plugin/PluginManager(610): pocketmine\plugin\PharPluginLoader->enablePlugin(DevTools\DevTools object)
01.10 17:42:35 [Server] Server thread/DEBUG #11 src/pocketmine/Server(1938): pocketmine\plugin\PluginManager->enablePlugin(DevTools\DevTools object)
01.10 17:42:35 [Server] Server thread/DEBUG #12 src/pocketmine/Server(1924): pocketmine\Server->enablePlugin(DevTools\DevTools object)
01.10 17:42:35 [Server] Server thread/DEBUG #13 src/pocketmine/Server(1633): pocketmine\Server->enablePlugins(integer 0)
01.10 17:42:35 [Server] Server thread/DEBUG #14 src/pocketmine/PocketMine(556): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///custom-php7.2.phar/, string /, string /plugins/)
01.10 17:42:35 [Server] Server thread/DEBUG #15 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)
01.10 17:42:35 [Server] Server thread/CRITICAL Could not load plugin 'ArenaPvP'

**Comment by IrishPacks** [comment]
Use the latest commit.
