### ISSUE TITLE
Cannot use ranked or unranked matches

### ISSUE THREAD

**Issue by NotRedd** [IrishPacks/ArenaPvP#31]
Cannot use ranked or unranked matches
Dosent say found ranked match.

- Plugin: 1.2.5
- Pocketmine-MP: PocketMine-MP 1.7dev-941
- PHP:  7.2

**Comment by IrishPacks** [comment]
I'll need more information as I cannot reproduce this issue. You must have an arena type that matches the kit type.

**Comment by NotRedd** [comment]
Basically you can't use the diamond or gold sword to find matches ill try rn on my ne2 host.

**Comment by NotRedd** [comment]
New•

**Comment by isoz** [comment]
And a bit offtopic but a UI menu would be much better than inventory menu. PE people seem to have a lot of difficulty doing stuff.

**Comment by isoz** [comment]
Well it found a match now, but there was 2 people queued before and it didn't initiate the match only when a third one queued it did, so I think it could be related to ELO, some kind of match making?

**Comment by isoz** [comment]
Oh.. Ok.. after looking at the code it seems you have a windows 10 verification and only matches with other windows 10...

**Comment by artulloss** [comment]
@isoz interesting, was the testing of the queue done on phone, because I tested it on win10

**Comment by isoz** [comment]
I simply opened the server to multiple users, I wasn't getting any match because I was on windows 10 and they were on PE, then the windows 10 user joined and I got a match. Then I checked the code and noticed the plugin checks if the person's OS is win10 and removed that check.

**Comment by artulloss** [comment]
@isoz good to know, wasn't aware of the issue as my server is primarily win10

**Comment by IrishPacks** [comment]
It's not a check, it's a separate queue, but I digress. I plan on adding a separate configuration for these things.
