### ISSUE TITLE
Arena's open but when dueling says none available

### ISSUE THREAD

**Issue by artulloss** [IrishPacks/ArenaPvP#32]
No errors in console

It seemed to work earlier but it glitches sometimes.

Parties don't work as well, no errors but nothing happens when used.

Seems like there are a lot of glitches at the moment, when a match fails to start it keeps you in it and you can't try again.

Another thing I noticed was that when setting the arena type in the config it says type 0 regardless of the pvp type, not sure if this is a bug ?

I tried editing the json manually and that just seemed to make it worse, I made sure to validate it before hand and it wouldn't work. I assigned each of the types a numerical value from 0-6 because I assumed it was an array. I also copied the data for multiple arenas, all different worlds but just copies of each other. Upon doing this the arena count command returned only 1. I'm assuming it has something to do with ID's ?

**Comment by IrishPacks** [comment]
I'll look into that.

**Comment by artulloss** [comment]
Unrelated but since I can't message you I have a kind of important question. With the plugins slapper and advanced kits, with a cooldown, how could a player lag out a server. I'm having this issue as another server is doing this to attack mine because they can't get players when my server is on. The method I think they're using is autoing with 100cps range. I added a cooldown to combat this and it seemed to work for a while however they must have found a new way to do it ): because I'm having the issue again. I can't just ip ban them because they have numerous dedicated machines which they use to as vpns or something and Muqsits proxy blocker stopped working.

**Comment by artulloss** [comment]
Well this has been fixed now, closing. Solved the other issue with autoclacking anticheat lmao
