### ISSUE TITLE
Only one arena when restarts

### ISSUE THREAD

**Issue by artulloss** [IrishPacks/ArenaPvP#33]
Adding multiple arenas then restarting causes only one arena to be open
The config keeps all the arenas in it.

**Comment by CaptainDuck** [comment]
Hmm.. the same thing is happening to me too, there are no logs in the console that says how many arenas are loaded or any debugs, when the plugin loads, only one arena loads when there are multiple, I think this is a config problem.

Here is my config
`
---
arenas:
- pos1:
  - 40
  - 60
  - 7
  pos2:
  - -42
  - 60
  - 7
  edge1:
  - 112
  - 60
  - -105
  edge2:
  - -135
  - 136
  - 109
  levelName: arena1
  type: 0
  maxBuildHeight: 15
- pos1:
  - 494
  - 72
  - 111
  pos2:
  - 524
  - 72
  - 111
  edge1:
  - 549
  - 121
  - 69
  edge2:
  - 469
  - 62
  - 153
  levelName: arena7
  type: 0
  maxBuildHeight: 15
- pos1:
  - -48
  - 73
  - 45
  pos2:
  - -79
  - 74
  - 55
  edge1:
  - -2
  - 136
  - -6
  edge2:
  - -95
  - 37
  - 118
  levelName: PvpA
  type: 0
  maxBuildHeight: 20
- pos1:
  - 1340
  - 7
  - 666
  pos2:
  - 1334
  - 7
  - 694
  edge1:
  - 1311
  - 35
  - 704
  edge2:
  - 1371
  - 4
  - 652
  levelName: Halloween
  type: 2
  maxBuildHeight: 5
- pos1:
  - 65
  - 4
  - -21
  pos2:
  - 44
  - 6
  - -83
  edge1:
  - -2
  - 88
  - 1
  edge2:
  - 149
  - 4
  - -131
  levelName: pvpArena
  type: 1
  maxBuildHeight: 20
...
`
