### ISSUE TITLE
Plugin Issues

### ISSUE THREAD

**Issue by daniel022302** [IrishPacks/ArenaPvP#4]
Bugs;

01.10 18:23:04 [Server] Server thread/INFO Enabling ArenaPvP v1.2.0
01.10 18:23:04 [Server] Server thread/CRITICAL Error: "Class 'sys\arenapvp\utils\GoldenHead' not found" (EXCEPTION) in "ArenaPvP-master/src/sys/arenapvp/kit/KitManager" at line 37
01.10 18:23:04 [Server] Server thread/DEBUG #0 ArenaPvP-master/src/sys/arenapvp/ArenaPvP(83): sys\arenapvp\kit\KitManager->__construct(sys\arenapvp\ArenaPvP object)
01.10 18:23:04 [Server] Server thread/DEBUG #1 ArenaPvP-master/src/sys/arenapvp/ArenaPvP(52): sys\arenapvp\ArenaPvP->loadKitManager()
01.10 18:23:04 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PluginBase(90): sys\arenapvp\ArenaPvP->onEnable()
01.10 18:23:04 [Server] Server thread/DEBUG #3 DevTools.phar/src/FolderPluginLoader/FolderPluginLoader(125): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
01.10 18:23:04 [Server] Server thread/DEBUG #4 src/pocketmine/plugin/PluginManager(610): FolderPluginLoader\FolderPluginLoader->enablePlugin(sys\arenapvp\ArenaPvP object)
01.10 18:23:04 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1938): pocketmine\plugin\PluginManager->enablePlugin(sys\arenapvp\ArenaPvP object)
01.10 18:23:04 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1924): pocketmine\Server->enablePlugin(sys\arenapvp\ArenaPvP object)
01.10 18:23:04 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1710): pocketmine\Server->enablePlugins(integer 1)
01.10 18:23:04 [Server] Server thread/DEBUG #8 src/pocketmine/PocketMine(556): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///custom-php7.2.phar/, string /, string /plugins/)
01.10 18:23:04 [Server] Server thread/DEBUG #9 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)
01.10 18:23:04 [Server] Server thread/INFO Disabling ArenaPvP v1.2.0
01.10 18:23:04 [Server] Server thread/INFO The arenas have been reset!
01.10 18:23:04 [Server] Server thread/INFO ArenaPvP has been disabled!

**Comment by IrishPacks** [comment]
Check to see if the GoldenHead class is in the utils folder.

**Comment by daniel022302** [comment]
Ok

**Comment by daniel022302** [comment]
Worked thanks
