### ISSUE TITLE
Spectating causes respawn glitch where player comes back to life

### ISSUE THREAD

**Issue by artulloss** [IrishPacks/ArenaPvP#46]
This is rare, but a huge issue. If this isn't possible to fix it's better to remove spectating on death.

**Comment by IrishPacks** [comment]
Any logs when it happens?

**Comment by artulloss** [comment]
Nope, I can try to get a video if that's helpful, probably not because it's self explanatory.

**Comment by IrishPacks** [comment]
Anything to help would be appreciated.

**Comment by artulloss** [comment]
it seems like players can take damage and fly around when they are spectating

**Comment by IrishPacks** [comment]
ah, i know this issue.

**Comment by artulloss** [comment]
Ah ok

**Comment by artulloss** [comment]
I don't think this is related, closing
