### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Chaqs** [IrishPacks/ArenaPvP#49]
##Issue so i updated the plugin to 1.5.0 and when i do /party /duel /addarena /arena it says "use this command ingame when i am ingame please help

##Versions 1.5.0

- Plugin:ArenaPvP
- Pocketmine-MP:1.5.0 

- PHP:7.2

##Details to help reproduce issue

List any details or steps to help reproduce the issue.

##Further comments, backtraces, etc.
Submit anything that you believe is necessary in solving the issue.

Please avoid submitting full errors without markdown. Use tools
such as Pastebin, Github Gist, etc. to make the errors readable.

**Comment by JackNoordhuis** [comment]
https://github.com/IrishPacks/ArenaPvP/blob/126547deef7c083b5fb4cd5230a622083bc45d72/plugin.yml#L9
