### ISSUE TITLE
/duel issue

### ISSUE THREAD

**Issue by daniel022302** [IrishPacks/ArenaPvP#6]
01.10 19:00:02[Server]INFO Fatal error: Declaration of sys\arenapvp\utils\ArenaChestInventory::onClose(pocketmine\Player $who) must be compatible with pocketmine\inventory\ChestInventory::onClose(pocketmine\Player $who): void in /plugins/ArenaPvP-master/src/sys/arenapvp/utils/ArenaChestInventory.php on line 65

Leading to server crash

**Comment by IrishPacks** [comment]
Forgot to commit that one, that's my bad.

**Comment by IrishPacks** [comment]
If you'd like to check it out for yourself: https://github.com/IrishPacks/ArenaPvP/commit/8ff1e6e717a85e22c47351f0f9152e63ef6f131e#diff-4c940b0961251a5ce3ee0181336944a2R56
