### ISSUE TITLE
How to add Arena

### ISSUE THREAD

**Issue by daniel022302** [IrishPacks/ArenaPvP#7]
How can you add arena on the Arena file cause /addarena doesn't work
It's it like this?
arena:
-Kohi 1

**Comment by IrishPacks** [comment]
Why doesn't /addarena work? It should work correctly.

**Comment by daniel022302** [comment]
I /addarena world1 it shows me 
usage:/addarena [option]

**Comment by IrishPacks** [comment]
That's not how it works. I'll create a wiki page, but it's not that it doesn't work, it's that you don't understand how to use it.

**Comment by daniel022302** [comment]
Ok thanks

**Comment by IrishPacks** [comment]
Here is the wiki link to the commands. https://github.com/IrishPacks/ArenaPvP/wiki/Commands
