### ISSUE TITLE
Selecting the duel 

### ISSUE THREAD

**Issue by daniel022302** [IrishPacks/ArenaPvP#8]
When you /duel or rank queue it show you a chest with all the kits but when you click it nothing happens. You are also not able to put it in your inventory I don't know if this is because of the arena?
![screenshot_20171001-183949](https://user-images.githubusercontent.com/28458532/31057599-2c846086-a6dd-11e7-9ea3-674b4e1407df.png)

**Comment by IrishPacks** [comment]
Please use the latest version of the plugin for the best results.
